[profile.release]
panic = 'unwind'

[workspace]
members = [
	"node",
	"pallets/swap",
	"pallets/swap/rpc",
	"primitives",
	"runtime"
]

[patch.crates-io]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
sp-arithmetic = { git =  "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
sp-state-machine = { git =  "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }

pallet-timestamp = { git =  "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" } 
pallet-balances = { git =  "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" } 

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.1" }
