[profile.release]
panic = 'unwind'

[workspace]
members = [
	"node",
	"pallets/swap",
	"pallets/swap/rpc",
	"primitives",
	"runtime"
]

[patch.crates-io]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-arithmetic = { git =  "https://github.com/paritytech/substrate", branch = "master" }
pallet-timestamp = { git =  "https://github.com/paritytech/substrate", branch = "master" }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "master" }
