[package]
name = "xp-gateway-bitcoin-bridge"
version = "0.1.0"
authors = ["Alan WANG <alan1995wang@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
