name: ci

on:
  push:
    branches:
      - singleton
  pull_request:
    branches:
      - singleton

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 3

jobs:
  checks:
    name: Fmt-Clippy-Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly-2021-11-07
          components: rustfmt, rust-src, clippy
          target: wasm32-unknown-unknown
          override: true

    - name: 1-Format
      run: cargo fmt --all -- --check
    - name: 2-Clippy
      run: make clippy
    - name: 3-Test
      run: make test
