on: [push, pull_request]

name: ci-build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check to latest commit
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-11-07
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true
      - name: Rust format
        run: make format
      - name: Rust clippy
        run: make clippy
      - name: Rust tests
        run: make test
